"""Gearhead hero: a little robot monkey (Jumpman's role). 16x16 frames, facing right.

Built from a head block (rows 0-9) plus a per-pose body block (rows 10-15), auto-outlined.
"""
from pix import *

K = (30, 58, 41)
P = {
    "k": K,
    "D": (137, 162, 87),  # shade
    "B": (190, 220, 127),  # body
    "F": (238, 255, 204),  # face / glow
    "m": (77, 128, 97),  # dark metal detail
}

HEADS = {
    "right": """
................
.........F......
......BBDBB.....
.....BBBBBBB....
..BB.BBFFFFFB...
..BFDBFFFkFF....
..BBDBFFFkFFF...
.....BBFFFFFF...
......BBFkkF....
""",
    "blink": """
................
.........F......
......BBDBB.....
.....BBBBBBB....
..BB.BBFFFFFB...
..BFDBFFFFFF....
..BBDBFFkkFFF...
.....BBFFFFFF...
......BBFkkF....
""",
    "happy": """
................
.........F......
......BBDBB.....
.....BBBBBBB....
..BB.BBFFFFFB...
..BFDBFFkFkF....
..BBDBFFFFFFF...
.....BBFkkkkF...
......BBFkkF....
""",
    "dead": """
................
................
......BBDBBD....
.....BBBBBBB....
..BB.BBFFFFFB...
..BFDBFFkFkF....
..BBDBFFFkFFF...
.....BBFkFkFF...
......BBFFFF....
""",
    "back": """
................
.......F........
......BDB.......
.....BBBBB......
.BB.BBBBBBB.BB..
.BFDBBmmmBBDFB..
.BBDBBmFmBBDBB..
.....BmmmB......
......BBB.......
""",
}

BODIES = {
    "stand": """
..D..BBBBBB.....
.D...BBBFFBD....
.D...BBBFFBDF...
..DDBBBBBBB.....
.....mm..DD.....
....mmm..DDD....
""",
    "run1": """
..D..BBBBBB.....
.D...BBBFFBmm...
.D.DDBBBFFB.....
..D..BBBBBB.....
....mm....DD....
...mm......DD...
""",
    "run2": """
..D..BBBBBB.....
.D...BBBFFBD....
..D..BBBFFBDF...
...DBBBBBBB.....
......mDD.......
.......DD.......
""",
    "run3": """
..D..BBBBBB.....
.D...BBBFFBDD...
.D.mmBBBFFB.F...
..D..BBBBBB.....
....DD....mm....
...DD......mm...
""",
    "run4": """
..D..BBBBBB.....
.D...BBBFFBm....
..D..BBBFFBmF...
...DBBBBBBB.....
......Dmm.......
.......mm.......
""",
    "jump": """
..D..BBBBBB.DF..
.D...BBBFFBD....
.D..mBBBFFB.....
..DDmBBBBBB.....
....mm...DD.....
...mm.....DD....
""",
    "land": """
..D..BBBBBB.....
.D..BBBBFFBD....
..DDBBBBFFBDF...
....BBBBBBBB....
...mm.....DD....
................
""",
    "victory": """
................
................
F..............F
D..............D
D..............D
.D............D.
.D............D.
..D..........D..
..D.........D...
...DDBBBBBBDD...
.....BBBFFB.....
.....BBBFFB.....
..DDBBBBBBB.....
.....mm..DD.....
....mmm..DDD....
""",
    "climb1": """
.FD..BBBBBB.....
..DDBBBBBBBB....
.....BBBBBBBmm..
.....BBBBBB..mF.
.....DD...mm....
.....DD.........
""",
    "climb2": """
.....BBBBBB..DF.
....BBBBBBBBDD..
..mmBBBBBBB.....
.Fm..BBBBBB.....
....mm...DD.....
.........DD.....
""",
    "wrench_up1": """
................
................
................
................
................
..............F.
.............DD.
............D...
............D...
..D..BBBBBBD....
.D...BBBFFB.....
.D..mBBBFFB.....
..DDmBBBBBB.....
....mm....DD....
...mm......DD...
""",
    "wrench_up2": """
................
................
................
................
................
..............F.
.............DD.
............D...
............D...
..D..BBBBBBD....
.D...BBBFFB.....
.D..mBBBFFB.....
..DDmBBBBBB.....
......mDD.......
.......DD.......
""",
    "wrench_down1": """
..D..BBBBBB.....
.D...BBBFFBD....
.D..mBBBFFB.D...
..DDmBBBBBB..DF.
....mm....DD....
...mm......DD...
""",
    "wrench_down2": """
..D..BBBBBB.....
.D...BBBFFBD....
.D..mBBBFFB.D...
..DDmBBBBBB..DF.
......mDD.......
.......DD.......
""",
}


def build(head, body, head_dy=0, body_dy=0):
    h = grid(HEADS[head], P, 16, 9)
    rows = [r for r in BODIES[body].strip("\n").split("\n") if r.strip()]
    tall = len(rows) > 6
    b = grid(BODIES[body], P, 16, len(rows))
    c = Image.new("RGBA", (16, 16), CLEAR)
    c.alpha_composite(b, (0, (0 if tall else 9) + body_dy))
    c.alpha_composite(h, (0, head_dy)) if head_dy >= 0 else c.alpha_composite(h.crop((0, -head_dy, 16, 9)), (0, 0))
    return outline(c, K)


def climb_top(stage):
    """Hauling up over a ledge: only the upper body is visible above the girder."""
    full = build("back", "climb1" if stage == 1 else "climb2")
    c = Image.new("RGBA", (16, 16), CLEAR)
    cut = 9 if stage == 1 else 12
    c.alpha_composite(full.crop((0, 0, 16, cut)), (0, 16 - cut))
    return c


ZAP = {P["B"]: P["F"], P["F"]: P["B"], P["D"]: P["m"]}  # inverted flash while shorting out


def frames():
    f = {}
    f["stand"] = build("right", "stand")
    f["run_1"] = build("right", "run1")
    f["run_2"] = build("right", "run2", head_dy=-1, body_dy=-1)
    f["run_3"] = build("right", "run3")
    f["run_4"] = build("right", "run4", head_dy=-1, body_dy=-1)
    f["jump"] = build("right", "jump", head_dy=-1, body_dy=-1)
    f["climb_1"] = build("back", "climb1")
    f["climb_2"] = build("back", "climb2")
    f["climb_top_1"] = climb_top(1)
    f["climb_top_2"] = climb_top(2)
    f["land"] = build("right", "land", head_dy=1, body_dy=1)
    f["victory"] = build("happy", "victory")
    f["wrench_up_1"] = build("right", "wrench_up1")
    f["wrench_up_2"] = build("right", "wrench_up2", head_dy=-1, body_dy=-1)
    f["wrench_down_1"] = build("right", "wrench_down1")
    f["wrench_down_2"] = build("right", "wrench_down2", head_dy=-1, body_dy=-1)
    f["blink"] = build("blink", "stand")
    f["hurt"] = recolor(build("dead", "stand"), {k + (255,): v + (255,) for k, v in ZAP.items()})
    f["dead_zap_1"] = build("dead", "stand")
    f["dead_zap_2"] = f["hurt"]
    f["dead_spin_1"] = f["stand"].rotate(-90)
    f["dead_spin_2"] = f["stand"].rotate(180)
    f["dead_spin_3"] = f["stand"].rotate(90)
    f["dead"] = _flat()
    return f


def _flat():
    """Lying on its back, antenna drooped, X eyes."""
    d = build("dead", "stand").rotate(90)
    c = Image.new("RGBA", (16, 16), CLEAR)
    bbox = d.getbbox()
    d = d.crop(bbox)
    c.alpha_composite(d, ((16 - d.width) // 2, 16 - d.height))
    return c


ORDER = ["stand", "run_1", "run_2", "run_3", "run_4", "jump",
         "climb_1", "climb_2", "climb_top_1", "climb_top_2", "land", "victory",
         "wrench_up_1", "wrench_up_2", "wrench_down_1", "wrench_down_2", "blink", "hurt",
         "dead_zap_1", "dead_zap_2", "dead_spin_1", "dead_spin_2", "dead_spin_3", "dead"]

# ------------------------------------------------------------------ wrench (the hammer)
WP = {"k": K, "D": (137, 162, 87), "B": (190, 220, 127), "F": (238, 255, 204), "m": (77, 128, 97)}
WRENCH_UP = """
....BB..BB......
....BF..FB......
....BFFFFB......
.....BFFB.......
......FB........
......FB........
......FB........
......FB........
......DD........
......mm........
"""


def wrench_frames():
    up = outline(grid(WRENCH_UP, WP, 16, 16), K)
    down = up.rotate(-90)
    return [up, down]
