"""Small Gearhead props: wrench power-up, spark enemy, generator, bonus items. 16x16 each."""
from pix import *

K = (30, 58, 41)
P = {"k": K, "S": (48, 93, 66), "M": (77, 128, 97), "L": (137, 162, 87),
     "H": (190, 220, 127), "E": (238, 255, 204)}


def g(art):
    return outline(grid(art, P, 16, 16), K)


# Wrench held overhead (head up). The hero's hand sits on the handle's bottom end.
WRENCH_UP = g("""
................
................
...HH....HH.....
...HE....EH.....
...HEEEEEEH.....
....HEEEEH......
.....HEEH.......
......EH........
......EH........
......EH........
......EH........
......LL........
......MM........
................
................
................
""")
WRENCH_DOWN = WRENCH_UP.rotate(-90)

SPARK_1 = g("""
................
................
.......E........
......EH....E...
..E..EHHE..E....
...EEHEEHEE.....
....HEEEEEH.....
...EHEEEEEHE....
....HEEEEEH.....
.....EHEEHEE....
....E.EHHE..E...
...E...EH.......
........E.......
................
................
................
""")
SPARK_2 = g("""
................
................
....E......E....
.....E....EE....
......EHHEE.....
.....HEEEEH.....
..EEHEEEEEEHE...
....HEEEEEEH.EE.
...EHEEEEEEHE...
.....HEEEEH.....
.....EEHHE......
....EE....E.....
...E.......E....
................
................
................
""")

GENERATOR_1 = g("""
................
..SSSSSSSSSSSS..
..SLLLLLLLLLLS..
..SHHHHHHHHHHS..
..SSSSSSSSSSSS..
...SLLLEELLLS...
...SLLEELLLLS...
...SLEEEEELLS...
...SLLLLEELLS...
...SLLLEELLLS...
...SLLLLLLLLS...
..SSSSSSSSSSSS..
..SMSMSMSMSMSS..
..SSSSSSSSSSSS..
................
................
""")
GENERATOR_2 = g("""
....E.....E.....
..SSSSSSSSSSSS..
..SLLLLLLLLLLS..
..SEEEEEEEEEES..
..SSSSSSSSSSSS..
...SLLLEELLLS...
...SLLEELLLLS...
...SLEEEEELLS...
...SLLLLEELLS...
...SLLLEELLLS...
...SLLLLLLLLS...
..SSSSSSSSSSSS..
..SMSMSMSMSMSS..
..SSSSSSSSSSSS..
................
................
""")

BOLT = g("""
................
................
................
.....LLLLLL.....
....LHHHHHHL....
....LHSSSSHL....
....LHSkkSHL....
....LHSSSSHL....
.....LLLLLL.....
.......MM.......
......MLLM......
.......MM.......
......MLLM......
.......MM.......
................
................
""")
BATTERY = g("""
................
................
.......SS.......
.....LLLLLL.....
.....LHHHHL.....
.....LHEEHL.....
.....LHEEHL.....
.....LEEEEL.....
.....LHEEHL.....
.....LHEEHL.....
.....LHHHHL.....
.....MMMMMM.....
.....SSSSSS.....
................
................
................
""")
OILCAN = g("""
................
................
..........LL....
.........L.L....
....LLLL.L......
....LHHL.L......
..LLLLLLLL......
.LHHHHHHHHL.....
LHHEHHHHHHHLLLL.
LHHEHHHHHHHL...E
LHHHHHHHHHHL....
.LMMMMMMMMML....
..SSSSSSSSS.....
................
................
................
""")


def frames():
    return {
        "wrench_up": WRENCH_UP, "wrench_down": WRENCH_DOWN,
        "spark_1": SPARK_1, "spark_2": SPARK_2,
        "generator_1": GENERATOR_1, "generator_2": GENERATOR_2,
        "bolt": BOLT, "battery": BATTERY, "oilcan": OILCAN,
    }


# Where to draw the wrench relative to the hero frame's top-left (hero facing right).
WRENCH_OFFSET = {"wrench_up": (8, -6), "wrench_down": (11, 6)}
