"""Small Gearhead props: wrench power-up, spark enemy, generator, bonus items. 16x16 each."""
from pix import *
from palette import *

K = INK
P = {
    "o": INK,
    "0": STEEL[0], "1": STEEL[1], "2": STEEL[2], "3": STEEL[3], "4": STEEL[4],
    "y": AMBER[0], "a": AMBER[1], "A": AMBER[2],
    "e": CYAN[0], "E": CYAN[1], "w": CYAN[2], "W": WHITE,
    "r": RED[1], "R": RED[2], "q": RED[3], "Q": RED[0],
    "t": TEAL[1], "u": TEAL[2], "U": TEAL[3], "T": TEAL[0],
    "g": WORLD["g4"], "G": WORLD["g6"], "h": WORLD["g3"],
}


def g(art):
    return outline(grid(art, P, 16, 16), K)


# Wrench held overhead. The hero's hand sits on the handle's bottom end.
WRENCH_UP = g("""
................
................
...34....34.....
...42....42.....
...4432233......
....43322.......
.....432........
......42........
......42........
......42........
......42........
......aa........
......yy........
................
................
................
""")
WRENCH_DOWN = WRENCH_UP.rotate(-90)

SPARK_1 = g("""
................
.......w........
......wE....E...
..e..wEE...E....
...eEEwwEeE.....
....EwWWwE......
...EwWWWWwEe....
..eEwWWWWwE.....
....EwWWwEE.....
.....EwwEe.e....
....E..EE...e...
...e....E.......
........e.......
................
................
................
""")
SPARK_2 = g("""
................
....e......e....
.....E....E.....
......EwwE......
.....wwWWwE.....
.eEEwWWWWWwEEe..
....EwWWWWwE....
....EwWWWWwEe...
.....wwWWww.....
......EwwE......
.....E....E.....
....e......E....
...........e....
................
................
................
""")
SPARK_3 = SPARK_1.transpose(Image.FLIP_LEFT_RIGHT)
SPARK_4 = SPARK_2.transpose(Image.FLIP_TOP_BOTTOM)

GENERATOR_1 = g("""
.....2332.......
.....1221.......
..000000000000..
..022333333320..
..011111111110..
..01gGGGGGGg10..
..01ggGaGGGg10..
..01gGaaaGGg10..
..01gGGGaGGg10..
..01gggGaggg10..
..011111111110..
..0aoaoaoaoao0..
..0oaoaoaoaoa0..
..000000000000..
................
................
""")
GENERATOR_2 = g("""
..E..wEEw..E....
.....wWWw.......
..000000000000..
..022333333320..
..011111111110..
..01GGGGGGGG10..
..01GGGAGGGG10..
..01GGAAAGGG10..
..01GGGGAGGG10..
..01GGGAGGGG10..
..011111111110..
..0aoaoaoaoao0..
..0oaoaoaoaoa0..
..000000000000..
................
................
""")

BOLT = g("""
................
................
................
.....234432.....
....24444332....
....23333321....
....12222210....
.....111110.....
.......32.......
......2331......
.......21.......
......2331......
.......21.......
................
................
................
""")
BATTERY = g("""
................
................
.......33.......
.....uuuuut.....
.....uUUuut.....
.....uUuuut.....
.....uaaaat.....
.....uAAaay.....
.....uaaaay.....
.....uUuuut.....
.....uuuutt.....
.....tttttT.....
.....111110.....
................
................
................
""")
OILCAN = g("""
................
................
..........32....
.........3..2...
....rrrr.3......
....rqRr.2......
..rrrrrrrr......
.rqqRRRRRRr.....
rqqRRRRRRRr3332.
rqRRRRRRRRr....E
rRRRRRRRRRr.....
.rrrrrrrrrr.....
..QQQQQQQQQ.....
................
................
................
""")


def frames():
    return {
        "wrench_up": WRENCH_UP, "wrench_down": WRENCH_DOWN,
        "spark_1": SPARK_1, "spark_2": SPARK_2, "spark_3": SPARK_3, "spark_4": SPARK_4,
        "generator_1": GENERATOR_1, "generator_2": GENERATOR_2,
        "bolt": BOLT, "battery": BATTERY, "oilcan": OILCAN,
    }


# Where to draw the wrench relative to the hero frame's top-left (hero facing right).
WRENCH_OFFSET = {"wrench_up": (8, -6), "wrench_down": (11, 6)}
