"""Firefly (Galaga clone) bird enemies. Top-down, facing up, 16x16, black outline like Sweet Sam's bear/bee."""
from pix import *

K = (0, 0, 0)
P = {
    "K": K,
    "W": (255, 241, 232),  # white (bear/bee)
    "L": (194, 195, 199),  # light grey
    "D": (95, 87, 79),  # dark grey
    "N": (29, 43, 83),  # navy
    "G": (0, 228, 54),  # green
    "g": (0, 135, 81),  # dark green
    "Y": (255, 221, 52),  # yellow (bee)
    "O": (255, 132, 38),  # orange (hive)
    "B": (171, 82, 54),  # brown (hive)
    "R": (255, 0, 77),  # red (bear)
    "r": (126, 37, 83),  # dark purple/maroon
    "U": (41, 173, 255),  # blue (bee)
    "u": (131, 118, 156),  # lavender
    "P": (148, 33, 106),  # bear purple
    "p": (255, 119, 168),  # pink
    "F": (255, 204, 170),  # peach
}

# ---------------------------------------------------------------- duck (grunt)
DUCK_A = """
................
......KKKK......
.....KOOOOK.....
.....KOOOOK.....
....KGGGGGGK....
....KGKGGKGK....
....KgGGGGgK....
.KK..KWWWWK..KK.
KWLKKBBBBBBKKLWK
KWWLLKBBBBKLLWWK
.KWLUUKBBKUULWK.
..KWUUKLLKUUWK..
...KKKLLLLKKK...
.....KLLLLK.....
.....KDDDDK.....
......KKKK......
"""
DUCK_B = """
................
......KKKK......
.....KOOOOK.....
.....KOOOOK.....
....KGGGGGGK....
....KGKGGKGK....
....KgGGGGgK....
.....KWWWWK.....
...KKBBBBBBKK...
..KWLKBBBBKLWK..
..KWLLKBBKLLWK..
..KWLUKLLKULWK..
...KWUKLLKUWK...
...KKWKLLKWKK...
.....KKDDKK.....
......KKKK......
"""

# ---------------------------------------------------------------- swallow (fast escort)
SWALLOW_A = """
................
.......KK.......
......KDDK......
.....KRRRRK.....
.....KKUUKK.....
..K...KUUK...K..
.KUK.KUUUUK.KUK.
KUUUKKUUUUKKUUUK
KWUUUUUUUUUUUUWK
.KWWUUUUUUUUWWK.
..KKWWKUUKWWKK..
....KKKUUKKK....
.....KUKKUK.....
....KUK..KUK....
....KUK..KUK....
.....K....K.....
"""
SWALLOW_B = """
................
.......KK.......
......KDDK......
.....KRRRRK.....
.....KKUUKK.....
......KUUK......
.....KUUUUK.....
....KUKUUKUK....
...KUUKUUKUUK...
...KUUKUUKUUK...
...KWUKUUKUWK...
...KWKKUUKKWK...
....K.KUUK.K....
.....KUKKUK.....
....KUK..KUK....
.....K....K.....
"""

# ---------------------------------------------------------------- parrot (diver)
PARROT_A = """
................
.......YY.......
......YYYY......
......RRRR......
.....RKRRKR.....
......RRRR......
.GG...RRRR...GG.
GGGGG.RRRR.GGGGG
GYYGGGRRRRGGGYYG
.UUYYGGRRGGYYUU.
..UU.GGRRGG.UU..
......RRRR......
......UYYU......
......UYYU......
.......UU.......
................
"""
PARROT_B = """
................
.......YY.......
......YYYY......
......RRRR......
.....RKRRKR.....
......RRRR......
....G.RRRR.G....
...GGGRRRRGGG...
...GYYGRRGYYG...
...UUYGRRGYUU...
....UU.RR.UU....
......RRRR......
......UYYU......
......UYYU......
.......UU.......
................
"""

# ---------------------------------------------------------------- owl (boss, two hits)
OWL_A = """
................
....P......P....
....PP.PP.PP....
....PPPPPPPP....
....PWWPPWWP....
....WYKWWKYW....
....PWWOOWWP....
.PP..PPOOPP..PP.
PPPPPFFPPFFPPPPP
PFPPFFPFFPFFPPFP
.PFFPPFFFFPPFFP.
..PP.FPFFPF.PP..
.....FPFFPF.....
......PFFP......
......O..O......
................
"""
OWL_B = """
................
....P......P....
....PP.PP.PP....
....PPPPPPPP....
....PWWPPWWP....
....WYKWWKYW....
....PWWOOWWP....
...PPPPOOPPPP...
..PPPFFPPFFPPP..
..PFPFPFFPFPFP..
...PFPFFFFPFP...
....PPFPPFPP....
.....FPFFPF.....
......PFFP......
......O..O......
................
"""


def make(art, auto_outline):
    im = grid(art, P)
    return outline(im, K) if auto_outline else im


# Boss "damaged" palette swap, like Boss Galaga turning purple after the first hit.
OWL_HURT = {P["P"]: P["U"], P["F"]: P["W"]}

BIRDS = {
    "duck": (DUCK_A, DUCK_B, False),
    "swallow": (SWALLOW_A, SWALLOW_B, False),
    "parrot": (PARROT_A, PARROT_B, True),
    "owl": (OWL_A, OWL_B, True),
}


def frames():
    out = {}
    for name, (a, b, auto) in BIRDS.items():
        out[name] = [make(a, auto), make(b, auto)]
    out["owl_hurt"] = [recolor(f, OWL_HURT) for f in out["owl"]]
    return out
